"""This file contains sample configuration for training and evaluation. of different models."""

# general settings
seed: 0

# data folders
train_image_folders:
  - "datasets/train/images/"
 # - "datasets/massachusetts_384/images/"
 # - "datasets/kaggle/images/"
train_gt_folders:
  - "datasets/train/groundtruth/"
  #- "datasets/massachusetts_384/groundtruth/"
 # - "datasets/kaggle/groundtruth/"
val_image_folders:
  - "datasets/validation/images/"
val_gt_folders:
  - "datasets/validation/groundtruth/"

weighted_random_sampler: False 

# data transforms
random_resized_crop: False
output_size: [400, 400]
input_size: 400
random_resized_crop_scale: [0.5, 0.5]
random_horizontal_flip: True
random_vertical_flip: True
random_rotation: True
degrees: 10
color_jitter: False
brightness: 0.1
contrast: 0.1
saturation: 0.1
hue: 0.1

# normalization
normalization: True
normalization_flag: "A" # "A" for AIcrowd, "AM" for AIcrowd + Massachusetts, "AK" for AIcrowd + Kaggle

# data loaders
batch_size: 3
train_size: 0.8
val_size: 0.2

# model settings
# UNetV1
model_name: 'UNetV1'
model_pretrained: False
model_scale: 0.5
model_save_name: 'models/checkpoints/unetv1-1.pt'
# UNetV2
model_name: "UNetV2",
model_in_channels: 3,
model_out_channels: 1,
model_init_features: 32,
model_pretrained: False,
model_save_name: "models/checkpoints/unetv2-1.pt",
# UNetV3
model_name: "UNetV3",  # Change for v3
model_save_name: "models/checkpoints/unetv3-effnetb3.pt",
# DeepLabV3 with ResNet50 backbone
model_pretrained: False
model_save_name: "models/checkpoints/deeplabv3_resnet50.pt",

# optimizer settings
optim_name: "adam"
optim_lr: 0.00003
optim_momentum: 0.9

# training settings
n_steps: 3000
eval_freq: 100

# eval
ckpt_save_dir: "./checkpoints/default-run",

# wandb logging
use_wandb: False  # set to True to enable wandb logging
wandb_project: "road-segmentation-clahe"
wandb_run: "deeplabv3-resnet50_large"
entity: "feeit" # delete this